### ISSUE TITLE
OBottle 2.0 \c\t.php has an arbitrary file write vulnerability（After login）

### ISSUE THREAD

**Issue by ddddbhm** [SomeBottle/OBottle#7]
If you don't think it's important, you can ignore me.

The trigger point is here:

c\t.php

![5](https://user-images.githubusercontent.com/56290390/102704150-95d04b80-42b2-11eb-8c23-949f8e2de57b.png)

We want to enter here, first of all, there are several conditions:

1.Sign in

![6](https://user-images.githubusercontent.com/56290390/102704152-9a94ff80-42b2-11eb-9e57-f2f9adf1a563.png)

2.

![65](https://user-images.githubusercontent.com/56290390/102704166-cf08bb80-42b2-11eb-88c1-be1f712678a2.png)

We first visit the login interface to enter the background:

/a/index.php

![7](https://user-images.githubusercontent.com/56290390/102704156-9ff24a00-42b2-11eb-9dd7-ee1aac29ef53.png)

Then we type payload in the title:    ";phpinfo();//

![8](https://user-images.githubusercontent.com/56290390/102704168-d760f680-42b2-11eb-88fd-0244495931bc.png)

Then it will automatically jump to the published page:

![9](https://user-images.githubusercontent.com/56290390/102704172-df209b00-42b2-11eb-99b5-42549cd98ad5.png)

**Comment by SomeBottle** [comment]
Thank you for finding out the vulnerability, it is of great help to me! 
This project is the exercise of my earlier coding days , so I need to review it for a while.
After finishing my college final exams, I'll try to figure it out

**Comment by SomeBottle** [comment]
I've fixed that, thank you!
